### ISSUE TITLE
Identify file format based on filename

### ISSUE THREAD

**Issue by pims** [turbinelabs/rotor#1]
Hi there,

I was very excited to try Rotor this morning, using `rotor version 0.16.0` and ran into a small documentaion/UX issue:

While following the instructions in the README to start with *Flat Files* Service Discovery, the README doesn’t mention that to use a YAML file – in the format described – one needs to specify the `--format=yaml` flag to Rotor.

Otherwise Rotor tries to parse the YAML as JSON, which is the default value in the `github.com/turbinelabs/codec` library and spits out `file: invalid character ' ' in numeric literal` errors with no obvious clue as to what is causing this.

I looked into trying to guess the file format from the filename, but it looks it would require quite a few changes to the way flags are parsed.

**Comment by 9len** [comment]
Hi @pims,

We'll update the README to be more precise, but will continue to require that the format be explicitly specified.
