### ISSUE TITLE
Dynamically watch namespaces in kubernetes

### ISSUE THREAD

**Issue by chrisgoffinet** [turbinelabs/rotor#10]
Currently the Kubernetes plugin requires a namespace to be defined to watch for pods. In a multi-tenant cluster I think this isn't going to be scalable. I propose we support, similar to Istio, the ability to label namespaces we want to be watched, and then Rotor can dynamically watch multiple namespaces.

**Comment by 9len** [comment]
Yeah, this is a good idea. We'll add it to our internal backlog.

**Comment by 9len** [comment]
@chrisgoffinet how would you propose to handle name conflicts when watching multiple namespaces? should namespaces be a part of the cluster name when they are non-default? That would allow backwards compatibility with existing behavior, while avoiding collision.

**Comment by chrisgoffinet** [comment]
@9len I think thats a sane default. I was trying to think of cases where a user would want to make his pods apart of the same `tbn_cluster` but run in different namespaces. I can't come up with a good reason why they would ever want to do that.
