### ISSUE TITLE
mechanism to configure custom clusters and listeners

### ISSUE THREAD

**Issue by 9len** [turbinelabs/rotor#14]
the plan is to add flags to read from a file to specify:

- statically configured listeners (with embedded routes)
- statically configured clusters
- a template for new listeners
- a template for new clusters

This covers many use-cases, but will not cover fully-dynamic specification of listeners and clusters; we plan to offer that in our paid product.

**Comment by vaibhav-sinha** [comment]
@9len Do you have an ETA for this?

**Comment by 9len** [comment]
Late June.

**Comment by 9len** [comment]
(missed by two days. will push the change today or tomorrow)

**Comment by 9len** [comment]
this landed in 7acd7cd08a3512d0424a6b742033abb5d50f295c, available in the [`0.18.0`](https://github.com/turbinelabs/rotor/commits/0.18.0) tag.
