### ISSUE TITLE
Consul health_check not work

### ISSUE THREAD

**Issue by wrfly** [turbinelabs/rotor#22]
Since consul reject the `:` as service's metadata key, the health_check didn't work.

```txt
{{bold "Health Checks"}}

Node health checks will be added as instance metadata named following the pattern
"check:<check-id>" with the check status as value. Additionally "node-health" is
added for an instance within each cluster to aggregate all the other health
checks on that node that either are 1) not bound to a service or 2) bound to
the service this cluster represents. The value for this aggregate metadata will be:

    passing   if all Consul health checks have a "passing" value
    mixed     if any Consul health check has a "passing" value
    failed    if no Consul health check has the value of "passing"
```

https://github.com/hashicorp/consul/issues/4422

**Comment by wrfly** [comment]
This is my config:

```json
{
  "services": [{
    "address": "10.6.8.102",
    "name": "id.102.co",
    "tags": ["envoy"],
    "port": 6061,
    "id": "id-1",
    "meta": {
      "check:id.102.co:1": "passing"
    }
  },
  {
    "address": "10.6.8.102",
    "name": "id.102.co",
    "tags": ["envoy"],
    "port": 6062,
    "id": "id-2",
    "meta": {
      "check:id.102.co:2": "passing"
    }
  },
  {
    "address": "10.6.8.102",
    "name": "id.102.co",
    "tags": ["envoy"],
    "port": 6063,
    "id": "id-3",
    "meta": {
      "check:id.102.co:3": "passing"
    }
  },
  {
    "address": "10.6.8.102",
    "name": "id.102.co",
    "tags": ["envoy"],
    "port": 6064,
    "id": "id-4",
    "meta": {
      "check:id.102.co:4": "passing",
      "check:id.102.co:5": "passing"
    }
  }],

  "checks": [
    {
      "id": "id.102.co:1",
      "http": "http://10.6.8.102:6061/ping",
      "method": "GET",
      "interval": "10s",
      "timeout": "1s"
    },
    {
      "id": "id.102.co:2",
      "http": "http://10.6.8.102:6062/ping",
      "method": "GET",
      "interval": "10s",
      "timeout": "1s"
    },
    {
      "id": "id.102.co:3",
      "http": "http://10.6.8.102:6063/ping",
      "method": "GET",
      "interval": "10s",
      "timeout": "1s"
    },
    {
      "id": "id.102.co:4",
      "http": "http://10.6.8.102:6064/ping",
      "method": "GET",
      "header": {"x-foo":["bar", "baz"]},
      "interval": "10s",
      "timeout": "1s"
    },
    {
      "id": "id.102.co:5",
      "tcp": "10.6.8.102:6064",
      "interval": "10s",
      "timeout": "1s"
    }
  ]
}
```

**Comment by 9len** [comment]
This seems like a consul bug?

**Comment by wrfly** [comment]
I don't know... So I made issues to both of the projects :thinking: 

If `consul` doesn't think it's a bug but a "design", I think `rotor` have to make change for it...

BTW, I didn't find the code related to `consul metadata` -> `envoy health_check`, would you mind point that to me? Thank you.

**Comment by 9len** [comment]
Can you include the rotor output?

**Comment by wrfly** [comment]
What do you mean by "include the rotor output", I don't understand :thinking:

**Comment by 9len** [comment]
I mean  Jen you run rotor, what output do you get on stdout. Please run with ROTOR_CONSUL_LEVEL=debug. 

The relevant rotor code is here:

https://github.com/turbinelabs/rotor/blob/d2bcae9c812717147c2a4172c7b5139c093771b7/plugins/consul/consul.go#L310

There is no conversion from consul health checks to envoy heath checks, instead the result of the consul check is exposed as metadata on the cluster instance. 

Can you better explain what “doesn’t work” means to you? What behavior are you seeing, and what we’re you expecting?

**Comment by wrfly** [comment]
Oh, I always think that `rotor` can convert the health check of `consul` to `envoy`'s health check. Because I saw some code about that:
https://github.com/turbinelabs/rotor/blob/083488d2cd5b9cc20d6c1a1f3dec33a014132695/xds/adapter/cds.go#L128-L148

I want to use envoy's health check for every "hosts" or "endpoints" in the cluster, I think rotor can convert them.

For now, rotor can only pass "clusters" and their "hosts", and the metadata doesn't influence any but add headers only, right?

**Comment by 9len** [comment]
The code you reference is part of our commercial product, where you can store envoy health checks in our API. 

if you already have custom listeners declared, you can set up [subset load balancing](
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/load_balancing.html#arch-overview-load-balancer-subsets) to only route to healthy hosts. 

I could see adding a flag to the rotor consul collector to filter unhealthy hosts. That’s something we could do for a future rotor release.

**Comment by wrfly** [comment]
Thank you, I'm trying to drop the unhealthy hosts.
