### ISSUE TITLE
Get error on docker build

### ISSUE THREAD

**Issue by lilida** [turbinelabs/rotor#3]
Just forked and try to docker build on it. Got the following errors.  Any idea?

Step 10/21 : RUN go get github.com/turbinelabs/rotor/...
 ---> Running in 7d210f05d73c
package github.com/lyft/protoc-gen-validate/tests/harness/cases/go: cannot find package "github.com/lyft/protoc-gen-validate/tests/harness/cases/go" in any of:
	/usr/local/go/src/github.com/lyft/protoc-gen-validate/tests/harness/cases/go (from $GOROOT)
	/go/src/github.com/lyft/protoc-gen-validate/tests/harness/cases/go (from $GOPATH)
package github.com/lyft/protoc-gen-validate/tests/harness/cases/other_package/go: cannot find package "github.com/lyft/protoc-gen-validate/tests/harness/cases/other_package/go" in any of:
	/usr/local/go/src/github.com/lyft/protoc-gen-validate/tests/harness/cases/other_package/go (from $GOROOT)
	/go/src/github.com/lyft/protoc-gen-validate/tests/harness/cases/other_package/go (from $GOPATH)
package github.com/lyft/protoc-gen-validate/tests/harness/cases/gogo: cannot find package "github.com/lyft/protoc-gen-validate/tests/harness/cases/gogo" in any of:
	/usr/local/go/src/github.com/lyft/protoc-gen-validate/tests/harness/cases/gogo (from $GOROOT)
	/go/src/github.com/lyft/protoc-gen-validate/tests/harness/cases/gogo (from $GOPATH)
package github.com/lyft/protoc-gen-validate/tests/harness/cases/other_package/gogo: cannot find package "github.com/lyft/protoc-gen-validate/tests/harness/cases/other_package/gogo" in any of:
	/usr/local/go/src/github.com/lyft/protoc-gen-validate/tests/harness/cases/other_package/gogo (from $GOROOT)
	/go/src/github.com/lyft/protoc-gen-validate/tests/harness/cases/other_package/gogo (from $GOPATH)

**Comment by 9len** [comment]
That's troubling. Will have a look.

**Comment by 9len** [comment]
@lilida are you building from the fork? you will probably have to change `go get github.com/turbinelabs/rotor/...` to `go get github.com/lilida/rotor/...` in the Dockerfile.

Have you added any new code, or are you building from a fresh clone?

**Comment by lilida** [comment]
@9len Yeah. You are right.

**Comment by lilida** [comment]
@9len Actually it is still turbinelabes under src. One thing is that the /test are in the .gitignore in lyft repo  https://github.com/lyft/protoc-gen-validate/blob/master/.gitignore

**Comment by 9len** [comment]
Just so I'm clear on your setup, is this right?

- you cloned your fork into $GOPATH/src/turbinelabs/rotor
- from that dir, you ran `docker build .`
- :boom:

I followed these steps and am still unable to reproduce. I have a suspicion, but it's hard to prove without repro.

**Comment by lilida** [comment]
Yes. NVM. I think it is related to my local Mac docker (network or disk). Tried to run go install locally and a separate linux box looks fine. I will just close this. Thanks for helping.

**Comment by 9len** [comment]
OK! Thanks for the prompt feedback, let us know if you need any other help.
