### ISSUE TITLE
Improve kubernetes example for rotor

### ISSUE THREAD

**Issue by chrisgoffinet** [turbinelabs/rotor#5]
As best practice we should create a namespace for rotor, so when using `kubectl create` namespaces are created, service accounts get setup, etc without user needing to fiddle with it.

* Create a namespace out of the box for rotor
* Assign service accounts, etc to use this namespace

**Comment by chrisgoffinet** [comment]
Fixes #6

**Comment by 9len** [comment]
fixed by a98c595b43543ab9ff60dfa540af215e14c33aa9
